# a=int(input("birinchi sonni k:"))
# b=int(input("ikkinchi sonni k:"))
# print(f"ikki sonning yigindisi:{a+b}")
# a=int(input("birinchi sonni k:"))
# b=int(input("ikkinchi sonni k:"))
# print(f"ikki sonning yigindisi:{a+b}")
# a=int(input("birinchi sonni k:"))
# b=int(input("ikkinchi sonni k:"))
# print(f"ikki sonning yigindisi:{a+b}")
# a=int(input("birinchi sonni k:"))
# b=int(input("ikkinchi sonni k:"))
# print(f"ikki sonning yigindisi:{a+b}")
# a=int(input("birinchi sonni k:"))
# b=int(input("ikkinchi sonni k:"))
# print(f"ikki sonning bolinmasi:{a//b}")
# birinchi_son=int(input("birinchi sonni k:"))
# ikkinchi_son=int(input("ikkinchi sonni k:"))
# birinchi_son=int(input("birinchi sonni k:"))
# ikkinchi_son=int(input("ikkinchi sonni k:"))
# print(f"{birinchi_son} - {ikkinchi_son} = {birinchi_son - ikkinchi_son}")
# print(str(birinchi_son) +"+"+ str(ikkinchi_son)+"="+ str(birinchi_son+ikkinchi_son))
# print(str(birinchi_son) +"/"+ str(ikkinchi_son)+"="+ str(birinchi_son/ikkinchi_son))
# print(f"{birinchi_son} * {ikkinchi_son} = {birinchi_son * ikkinchi_son}")
# print(f"{birinchi_son} * {ikkinchi_son} = {birinchi_son * ikkinchi_son}")
# print(f"{birinchi_son} - {ikkinchi_son} = {birinchi_son - ikkinchi_son}")
# print(f"{birinchi_son} / {ikkinchi_son} = {birinchi_son / ikkinchi_son}")


# narx=int(input("mahsulot narxi(so'm):"))
# soni=int(input("nechta olasiz?"))
# print("umumiy summa:",narx*soni,"so'm")
# daromad=int(input("oylik daromadingiz(so'm):"))
# soliq=daromad*0.12
# print("soliq:",soliq,"so'm")
# a=input("1-mahsulot:")
# b=input("2-mahsulot:")
# c=input("3-mahsulot:")
# print("bozor ro'yxati:",[a,b,c])
# mashina=input("qaysi mashina sizga yoqadi?")
# print(mashina,"-yaxshi tanlov")
# km=float(input("necha km yurildi?"))
# print("to'lanadigan summa:", km*5000, "so'm")
# narx=int(input("taom narxi(so'm):"))
# ximat=narx*0.12
# print("xizmat haqi:", xizmat, "so'm")
# print("jami to'lov:", narx+xizmat,"so'm")
# narx=int(input("mahsulot narxi:"))
# yetkazish=30000
# print("umumiy to'lov:",narx+yetkazish,"so'm")
# palov=int(input("palov narxi:"))
# shashlik=int(input("shashlik narxi:"))
# choy=int(input("choy narxi:"))
# print("jami:",palov+shashlik+choy,"so'm")
# joy=input("qaysi qatordagi o'rinni tanlaysiz/")
# print("o'rin band qilindi:",joy)
# kurs=input("qaysi yo'nalishga chipta olas?")
# print("yonalish tanlandi:",yonalish)
# ism=input("kartaga yoziladigan ismingiz:")
# print("ism tasdiqlandi:",ism)
# dori=input("qanday dori kerak/")
# print("dori nomi qabul qilindi:",dori)
# taom=input("taom nomini kiriting:")
# narx=int(input("taom narxi qancha?"))
# soni=int(input("nechta buyurtma qilasiz?"))
# print("umumiy summa:", narx * soni, "so'm")
# km=float(input("necha km borasiz?"))
# print("taxi narxi:", km * 2500, "so'm")
# masofa=float(input("bosib o'tilgan masofa(km):"))
# sarf=float(input("mashina 80 kmda qancha benzin yeydi?"))
# print("ketadigan benzin:", masofa/ 80 * sarf,"litr")
# oquvchilar=int(input("o'quvchilar soni?"))
# sinf_soni=int(input("sinf soni"))
# ortacha=oquvchilar/ sinf_soni
# print("har bir sinfdagi o'rtacha o'quvchilar:", sinf_soni)
# narx=int(input("mahsulot narxi:"))
# chegirma=int(input("chegirma foizi %:"))
# yakuniy=narx-(narx * chegirma / 100)
# print("chegirmadan keyingi narx:",int(yakuniy), "so'm")
# olma=int(input("olma narxi:"))
# ananas=int(input("ananas narxi:"))
# yog=int(input("yog narxi:"))
# jami= olma+ananas+yog
# print("bozordagi umumiy xarajat:", jami,"so'm")
# narx=int(input("mahsulot narxi:"))
# pul=int(input("xaridor bergan pul:"))
# qaytim=pul-narx
# print("qaytim:", qaytim, "so'm")
# litr=float(input("necha litr benzin toldirdingiz:"))
# narx=float(input("1 litr benzin narxi (so'm):"))
# jami=litr * narx
# print("benzinga ketgan xarajat;", jami, "so'm")
# kunlik=int(input("kuniga nechta sigaret chekasiz:"))
# narx=int(input("1dona sigaret narxi (so'm):"))
# kun_xarajat=kunlik * narx
# oy_xarajat=kun_xarajat * 30
# print("kunlik xarajat:",kun_xarajat, "so'm")
# print("oylik xarajat:",oy_xarajat,("so'm"))
